from django.urls import path
from .geo import suggest_places
from .views import (
    BookingCancelView,
    BookingConfirmView,
    BookingListCreateView,
    CurrencyRatesView,
    LoginView,
    MyBookingsView,
    PaymentCreateView,
    ProfileView,
    RegisterView,
    ReviewCreateView,
    ReviewsByTourView,
    TourListView,
    TourDetailView,
    TourSimilarView,
    StayListView,
)
urlpatterns = [
    path("geo/suggest/", suggest_places, name="geo-suggest"),
    path("currency/rates/", CurrencyRatesView.as_view(), name="currency-rates"),
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('bookings/', BookingListCreateView.as_view(), name='booking-list-create'),
    path('bookings/my/', MyBookingsView.as_view(), name='my-bookings'),
    path('bookings/<int:id>/confirm/', BookingConfirmView.as_view(), name='booking-confirm'),
    path('bookings/<int:id>/cancel/', BookingCancelView.as_view(), name='booking-cancel'),
    path('payments/', PaymentCreateView.as_view(), name='payment-create'),
    path('tours/', TourListView.as_view(), name='tour-list'),
    path('tours/<int:tour_id>/', TourDetailView.as_view(), name='tour-detail'),
    path('tours/<int:tour_id>/similar/', TourSimilarView.as_view(), name='tour-similar'),
    path("reviews/<int:tour_id>/", ReviewsByTourView.as_view(), name="reviews-by-tour"),
    path("reviews/", ReviewCreateView.as_view(), name="review-create"),
    path("stays/", StayListView.as_view(), name="stay-list"),
]
