# Generated by Django 5.2.14 on 2026-05-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0004_alter_booking_created_at_alter_payment_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="lat",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="tour",
            name="lng",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]

