# Generated by Django 4.2.20 on 2026-05-28 11:42

from django.db import migrations, models


def copy_existing_content_to_russian_fields(apps, schema_editor):
    Tour = apps.get_model('tours', 'Tour')
    for tour in Tour.objects.all().only('id', 'title', 'description', 'title_ru', 'description_ru'):
        updates = {}
        if tour.title and not tour.title_ru:
            updates['title_ru'] = tour.title
        if tour.description and not tour.description_ru:
            updates['description_ru'] = tour.description
        if updates:
            Tour.objects.filter(pk=tour.pk).update(**updates)


def clear_backfilled_russian_fields(apps, schema_editor):
    Tour = apps.get_model('tours', 'Tour')
    Tour.objects.update(title_ru=None, description_ru=None)


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(copy_existing_content_to_russian_fields, clear_backfilled_russian_fields),
    ]
