# Generated by Django 5.2.14 on 2026-06-01 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tour_description_en_tour_description_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='accommodation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tour',
            name='equipment',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='excluded',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='guide_bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tour',
            name='guide_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tour',
            name='included',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='itinerary',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('available_spots', models.IntegerField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='tours.tour')),
            ],
        ),
    ]
