# Generated by Django 5.2.14 on 2026-06-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_tour_accommodation_tour_equipment_tour_excluded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(blank=True, default='', max_length=255)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('title_ky', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('location_ru', models.CharField(blank=True, default='', max_length=255)),
                ('location_en', models.CharField(blank=True, default='', max_length=255)),
                ('location_ky', models.CharField(blank=True, default='', max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('region_ru', models.CharField(blank=True, default='', max_length=255)),
                ('region_en', models.CharField(blank=True, default='', max_length=255)),
                ('region_ky', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='stays/')),
                ('badge', models.CharField(blank=True, default='', max_length=50)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('type', models.CharField(default='hotel', max_length=50)),
                ('max_guests', models.IntegerField(default=2)),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='stays',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.stay'),
        ),
    ]
