# Generated by Django 4.2.20 on 2026-05-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='cards',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
