# Generated by Django 4.2.20 on 2026-05-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aimessage_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['session_id', '-updated_at'], name='ai_aiconver_session_b5d754_idx'),
        ),
    ]
